-- CrowSocial production-oriented Supabase schema
create type public.app_role as enum ('USER','MODERATOR','ADMIN','OWNER');
create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,username text unique not null,display_name text not null,bio text,avatar_url text,role public.app_role not null default 'USER',verified boolean not null default false,created_at timestamptz not null default now());
create table public.posts(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,content text not null,image_urls text[] not null default '{}',created_at timestamptz not null default now());
create table public.post_likes(user_id uuid references public.profiles(id) on delete cascade,post_id uuid references public.posts(id) on delete cascade,created_at timestamptz default now(),primary key(user_id,post_id));
create table public.comments(id uuid primary key default gen_random_uuid(),post_id uuid not null references public.posts(id) on delete cascade,user_id uuid not null references public.profiles(id) on delete cascade,content text not null,created_at timestamptz default now());
create table public.comment_likes(user_id uuid references public.profiles(id) on delete cascade,comment_id uuid references public.comments(id) on delete cascade,primary key(user_id,comment_id));
create table public.followers(follower_id uuid references public.profiles(id) on delete cascade,following_id uuid references public.profiles(id) on delete cascade,created_at timestamptz default now(),primary key(follower_id,following_id),check(follower_id<>following_id));
create table public.conversations(id uuid primary key default gen_random_uuid(),created_at timestamptz default now());
create table public.conversation_members(conversation_id uuid references public.conversations(id) on delete cascade,user_id uuid references public.profiles(id) on delete cascade,primary key(conversation_id,user_id));
create table public.messages(id uuid primary key default gen_random_uuid(),conversation_id uuid references public.conversations(id) on delete cascade,sender_id uuid references public.profiles(id) on delete cascade,content text not null,created_at timestamptz default now(),read_at timestamptz);
create table public.notifications(id uuid primary key default gen_random_uuid(),user_id uuid references public.profiles(id) on delete cascade,type text not null,title text not null,body text,actor_id uuid references public.profiles(id) on delete set null,created_at timestamptz default now(),read_at timestamptz);
create table public.reports(id uuid primary key default gen_random_uuid(),reporter_id uuid references public.profiles(id) on delete set null,target_type text not null,target_id uuid not null,reason text not null,details text,status text not null default 'OPEN',created_at timestamptz default now(),resolved_at timestamptz);
create table public.verification_requests(id uuid primary key default gen_random_uuid(),user_id uuid references public.profiles(id) on delete cascade,reason text not null,status text not null default 'OPEN',created_at timestamptz default now(),reviewed_by uuid references public.profiles(id),reviewed_at timestamptz);
create table public.admin_logs(id uuid primary key default gen_random_uuid(),admin_id uuid references public.profiles(id) on delete set null,action text not null,target_user_id uuid references public.profiles(id) on delete set null,metadata jsonb default '{}',created_at timestamptz default now());
create table public.settings(key text primary key,value jsonb not null default '{}');
create index posts_created_at_idx on public.posts(created_at desc);create index comments_post_idx on public.comments(post_id);create index notifications_user_idx on public.notifications(user_id,created_at desc);
alter table public.profiles enable row level security;alter table public.posts enable row level security;alter table public.post_likes enable row level security;alter table public.comments enable row level security;alter table public.followers enable row level security;alter table public.notifications enable row level security;
create policy "profiles readable" on public.profiles for select using (true);create policy "own profile update" on public.profiles for update using(auth.uid()=id);create policy "posts readable" on public.posts for select using(true);create policy "own posts insert" on public.posts for insert with check(auth.uid()=user_id);create policy "own posts delete" on public.posts for delete using(auth.uid()=user_id);create policy "likes readable" on public.post_likes for select using(true);create policy "own likes" on public.post_likes for all using(auth.uid()=user_id) with check(auth.uid()=user_id);create policy "comments readable" on public.comments for select using(true);create policy "own comments" on public.comments for all using(auth.uid()=user_id) with check(auth.uid()=user_id);create policy "followers readable" on public.followers for select using(true);create policy "own follows" on public.followers for all using(auth.uid()=follower_id) with check(auth.uid()=follower_id);create policy "own notifications" on public.notifications for select using(auth.uid()=user_id);create policy "own notifications update" on public.notifications for update using(auth.uid()=user_id);
-- IMPORTANT: role changes and moderation actions should be implemented with SECURITY DEFINER functions and server-side checks, never from the browser.
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.profiles(id,username,display_name) values(new.id,coalesce(new.raw_user_meta_data->>'username',split_part(new.email,'@',1)),coalesce(new.raw_user_meta_data->>'display_name',split_part(new.email,'@',1))); return new;end;$$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
